language: php

php:
    - 7.2
    - 7.3
    - 7.4
    - nightly
    - hhvm

install:
    - composer install --prefer-dist

script:
    - mkdir -p build/logs
    - ./bin/phpunit --coverage-clover build/logs/clover.xml tests/

after_script:
    - ./bin/coveralls -v
