language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - nightly
    - hhvm

install:
    - composer install --prefer-dist

script:
    - mkdir -p build/logs
    - ./bin/phpunit --coverage-clover build/logs/clover.xml tests/

after_script:
    - ./bin/coveralls -v
